### ISSUE TITLE
Vibisility change event not triggered when focus switched to different application

### ISSUE THREAD

**Issue by stodge** [ai/visibilityjs#17]
I have the following code:

```
        this.listener = Visibility.change(function (e, state) {
            console.debug("Visibility: " + Visibility.state());
        });
```

The change function is only triggered in Chrome Version 46.0.2490.86 (64-bit) (OSX) when I change tabs. If I switch to another application or take focus away from the page, e.g. to the developer tools, the event isn't triggered.

**Comment by ai** [comment]
@stodge it is how Page Visibility API works. By some reason browsers check only tabs. Even if you lock screen, they didn’y fire a `hidden` state :(.

**Comment by stodge** [comment]
Ok - thanks. :)

**Comment by NeXTs** [comment]
@stodge http://codepen.io/jonathan/pen/sxgJl
