### ISSUE TITLE
Mark 1.2.3 as latest release

### ISSUE THREAD

**Issue by mrienstra** [ai/visibilityjs#21]
1.2.1 is still tagged as the latest release, which may be why cdnjs* has not picked up either 1.2.2 or 1.2.3.

It's almost certainly why 1.2.2 & 1.2.3 are currently "hidden" (behind a "Show 2 newer tags" message) when visiting https://github.com/ai/visibilityjs/releases

*: https://cdnjs.com/libraries/visibility.js

**Comment by ai** [comment]
I update Releases.

**Comment by ai** [comment]
PR to CDNJS was sent https://github.com/cdnjs/cdnjs/pull/7302

**Comment by ai** [comment]
1.2.3 was deployed to CDNJS

**Comment by mrienstra** [comment]
Awesome thanks!
