### ISSUE TITLE
Race condition on visibility change and Visibility.stop(timer) call in callback

### ISSUE THREAD

**Issue by mikhailv** [ai/visibilityjs#24]
I have following code on page for example:

```javascript
var startTime = Date.now();
var timer = Visibility.every(1000, function() {
  // ... some code ...
  if (Date.now() - startTime > 5000) Visibility.stop(timer);
});
```

If I switch to another page before 5 sec will expire and after 5 sec will return back on the page, callback will be called and `.stop(timer)` as well, but `every` timer will still work and there is no way to stop it after that. This is because `setInterval` is calling after callback call:

- https://github.com/ai/visibilityjs/blob/ecaa6bb6cb30e03a8d6573eb29ce364e554586f5/lib/visibility.timers.js#L120
- https://github.com/ai/visibilityjs/blob/ecaa6bb6cb30e03a8d6573eb29ce364e554586f5/lib/visibility.timers.js#L124

**Comment by ai** [comment]
Released in 1.2.4
