### ISSUE TITLE
Host a live demo

### ISSUE THREAD

**Issue by ajhsu** [ai/visibilityjs#27]
Hi @ai , I loved the way of the library providing a comfortable way to apply visibility API.
And I loved the way how it versioning with historical spacecraft names.

Here I have a suggestion that: it may host a live demo (like what integration test `test/integration.html` did) in `gh-pages` branch and put a hyperlink on readme file, so that developers can take a sneak peek about how visibility.js works in real-case.

If you're agree with this suggestion, I think I am available for working on a PR for it.

**Comment by ai** [comment]
Hi. Yeap, it is nice idea

**Comment by ajhsu** [comment]
Great! I'm going to work on this. Thanks for your supporting!
