### ISSUE TITLE
Can this work with server-side rendering?

### ISSUE THREAD

**Issue by elliotlings** [ai/visibilityjs#42]
Do you know whether this library can work with server-side rendering?

**Comment by ai** [comment]
As I know it should work without `document` and other browser-specific API. It will just think that the page is always visible.

If you will have any problems, please report. I will try to fix it quickly.

**Comment by mrlaseptima** [comment]
hi . @elliotlings
i use it in SSR in after js ,
you can check server side rendering and then use dynamic import 
`
 isServer() {
    return !(typeof window != "undefined" && window.document);
 }
 
 async chatBrowserNotif(title = "", options, onClick) {
    if (!isServer()) {
      //use dynamic import because this package cant run in server side
      const Visibility = await import("visibilityjs");
      if ("hidden" == Visibility.state()) {
        const notification = new Notification(title, {
          ...options,
        });

        notification.onclick = (e) => {
          onClick();
        };
      }
    }
  }
`
