### ISSUE TITLE
stop() not working

### ISSUE THREAD

**Issue by zorkind** [ai/visibilityjs#46]
I am running Visibility on Angular 1.5

It starts ok, but when i try to stop it, it just won't work.

`   if ($rootScope.hdRTimerId != undefined) 
        Visibility.stop($rootScope.hdRTimerId);`

This is how i am trying to stop it.

I am saving the id in the root scope so i don't lose it with page transitions, i won't have a problem because i am only using Visibility on 1 page, when i get back to the page, i try to run stop if the Id is set.

But it wont work and the callback is fired anyway :-(

**Comment by ai** [comment]
How did you started it?

**Comment by zorkind** [comment]
Sorry i forgot to add that.
`$rootScope.hdLTimerId = Visibility.every(5 * 1000, $scope.UpdateLeft);`

**Comment by ai** [comment]
Sorry, have no idea. This project is not really alive :D. If you will send PR, I will release it. But spend most of my open source investigation time on other projects.

**Comment by zorkind** [comment]
Oh i had no idea D: why is it not alive?

**Comment by ai** [comment]
Mostly because PostCSS and Autoprefixer are more popular. Logux and Size Limit could make Web better.

**Comment by ai** [comment]
Also, we don’t need polyfill right now, so using so big library just for `every` sugar is overkill.

**Comment by zorkind** [comment]
This is the only timer component i have ever used. :-\ I am a user for years hahaha

First time i am having an issue

**Comment by zorkind** [comment]
you think i should rollback to setTimeOut?

**Comment by ai** [comment]
Or just try to implement by yourself, it is very simple stuff

**Comment by ai** [comment]
> I am a user for years hahaha

Thanks :D

**Comment by zorkind** [comment]
I think the first time i used this was back in 2014, i made a huge graphic screen with this. The visibility thing is very important for me, since i am used to digest huge amounts of data from the network, and i need to do that only when needed, when people switch screens to use another "report" i want to stop the previous one and all that jazz.

Not the main reason why i am using it now, but back then, it was a very important thing.
This time i am really just using it because i trust it :)

**Comment by zorkind** [comment]
First time i am using it with Angular tho, so i am guessing the $scope thing have something to do with my issue. I will try to figure it out :)

**Comment by zorkind** [comment]
Ohhh i think i know what's going on.
It is probably reloading the JS when i am switching pages, making all counters go back to zero.
So it has nothing to stop.
But the SetInterval is still alive in the LIMBO :-(
