### ISSUE TITLE
Can you provide a UMD wrapped build in NPM?

### ISSUE THREAD

**Issue by chrisknoll** [ai/visibilityjs#47]
We're having an issue loading this module when using an AMD loader (like RequireJS). When run as a stand-alone, it works (because the module is exported to a global) but when bundled, the global is not set.

I can see about providing a PR where we just add the AMD detection to this part of the code:
https://github.com/ai/visibilityjs/blob/master/lib/visibility.core.js#L186

if it would be considered for inclusion.

**Comment by chrisknoll** [comment]
I'll submit a PR with the change we made locally to make it work in AMD. Btw: it was literally 2 lines of code.  I don't think 50 bytes is too much of a hardship, but you decide!

**Comment by ai** [comment]
What is a reason why do you use AMD instead of CommonJS or globals?

**Comment by chrisknoll** [comment]
AMD allows us to do development without any build toolchains.  Only the modules that are needed for a specific use case are downloaded (it's asynchronous) making development nice and streamlined.  When we're ready for production deployment, we do a build that optimizes the individual modules into an optimized-for-download bundle, but none of those steps get in the way of our dev cycle.

Most libraries out there support a UMD wrapper. Hopefully you will find that the 2 added lines of code isn't too much of a hardship to include in your library.

**Comment by ai** [comment]
> AMD allows us to do development without any build toolchains. 

Hope do you do minification (`a + b` > `a+b`), cache invalidation (`main.js` > `main.fa6e89.js`) without bundler?

**Comment by chrisknoll** [comment]
Feel free to check out our application here: https://github.com/OHDSI/Atlas.  You can see how our package.json sets up the build scripts.  Not sure what you mean by cache invalidation, but, I was hoping we could stay focused on the merits of this PR for inclusion. We'd rather not have to just maintain a fork over the AMD compatibility, but if that's what we need to do, that's what we need to do.

**Comment by chrisknoll** [comment]
Sounds simple! Would you be able to provide a PR for that change?

**Comment by ai** [comment]
Sorry, I spend all my open source for this week on Autoprefixer release.
